server:
  port: 0

spring:
    application:
      name: ms-account
    devtools:
      remote:
        restart:
          enabled: true

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
